# Generated by Django 4.1.2 on 2022-10-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configtbl',
            old_name='name',
            new_name='key',
        ),
        migrations.AddField(
            model_name='configtbl',
            name='desctiption',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
