# Generated by Django 4.1.2 on 2022-10-16 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_rename_name_configtbl_key_configtbl_desctiption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configtbl',
            name='desctiption',
        ),
    ]
