# Generated by Django 4.1.2 on 2022-10-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
