# Generated by Django 4.1.2 on 2022-10-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_monitor_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=21)),
                ('humidifier_event', models.BooleanField(default=False)),
                ('fan_event', models.BooleanField(default=False)),
                ('pump_event', models.BooleanField(default=False)),
                ('water_level_event', models.BooleanField(default=False)),
            ],
        ),
    ]
